### ISSUE TITLE
Pets: Installation instructions only work locally

### ISSUE THREAD

**Issue by JulianGro** [theanine3D/overte-addons#2]
When installing the Pets app as described in the README, it gets everything from the local file system which makes other people unable to see your pet.

I would suggest hosting it via GitHub Pages, or adding it to the [More app](https://github.com/overte-org/community-apps)

**Comment by theanine3D** [comment]
Thank you so you much for pointing this out! That was a huge oversight on my part.

I've now updated the script to load all assets remotely, from my GitHub account. Unfortunately, by running the app remotely from the github URL, your previous pet data won't transfer over. Overte appears to treat it as a completely new app. 

To use the new updated version, you'll want to remove the previous version you've installed, then load the following URL from the Running Scripts window.
https://theanine3d.github.io/pets/pets.js

**Comment by JulianGro** [comment]
Just FYI, on my end it just reads it from the Interface.json as normal. So even with the remote URL, my Tux is still alive.
